---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAZvuODxB/SlTKRuA1viTlazLblGzj8wspNWu332um4gwLszF8F57xMc7C22Ld9iVAkUnP8SMsMEpspI8UhSuBlNZbSyfqaEGZ9dDefRNLUuB1PLeQEagkJCvowm7Smwd0ns+s76gFxkPZxOkNYIXfpewp9WTfjYGYX5rYUJjzE2EbJ8fL1Q9BuMgcxQYSQOOWCcvQHorhSEogJKMD3MXHciwdwR6ZXkGbmV/UHZHx0skoQ3umytTLomTJKbX/VCPO3yUfRDQN8NA4ZGwAD/bQBAWV7oylFv0A6qam8/vvTapKzl4sqi95OOrQusw85k0/04PNiX14jhlit1YxA4nupVxYrqfyK5unzdfYdMk0S+WGqmto+7XWK6AhJEIpDLtJK7oLmjxDWvaBX3F/quJ8YZFEHgFhW2y7nDOz407lRN7OwLbJm0dnSbp6ijRdzgSYTIRw4ehX25n4GSmpWlguyHYvdZXTPRElxDoT3gCW9sE5Jk7MqgIpNpO8r+HilRRZkA2cJfYRhin2xQ/VBT9II6bu5ocJK3K24wIrGftk3W4noffNaAqTU/y/qhv8nlbng4tILOMo0pNfPW3V4nF+1ntIFy1QFYPvwEospW5dMiF6M8mEbUBqyJuG200j1kFsnfYKW9gF0tlKMxvLH0eOMYkXXmep72Ft+Z44ZWb0Ex2bL+QCj6eMJ+sG2qmON7N+ARV44AhJk4fwJoNCfnPysBRwYe3y33EiG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
